# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserPage',
            fields=[
                ('page_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('acces_token', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('facebook_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.User')),
            ],
        ),
    ]
