# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-11 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_integrated',
            field=models.BooleanField(default=False),
        ),
    ]
